# Build: windows nodejs 8.11
os: windows
language: node_js
node_js:
    - "12.14.1"
cache:
  directories:
    - "node_modules"

# Exclude untagged releases
branches:
  except:
    - /^untagged-/
    - /^build-/

# Install grunt and node-gyp
before_install:
- npm install -g grunt-cli node-gyp
- for /f "delims=" %P in ('npm prefix -g') do npm config set node_gyp "%P\node_modules\node-gyp\bin\node-gyp.js"
- npm install

install:
# Download Firebot
- git clone --depth=1 --branch=v5 https://github.com/crowbartools/Firebot.git
- cd Firebot
# Install Firebot's deps
- npm install
# Rebuild robotjs
- npm run rebuild
# Compile scss
- npm run compile:scssGui
- npm run compile:scssOverlay
# run packager
- electron-packager . Firebot --out=./dist --platform=win32 --arch=x64 --electronVersion=7.1.9 --js-flags="--harmony" --asar --prune --overwrite --version-string.ProductName="Firebot" --icon=./gui/images/logo.ico --ignore=/profiles --ignore=/resources --ignore=/doc --ignore=/.vscode
- cd ..

# Run grunt to move /resources/ into dist folder and zip the dist folder
script:
- grunt --verbose

# Tag build as build-YYYY-DD-MM-hh-mm-ss
before_deploy:
- git config --local user.name "CrowbarToolsRobot"
- git config --local user.email "crowbartoolsrobot@gmail.com"
- export TRAVIS_TAG=build-$(date +"%Y-%m-%d-%H-%M-%S")
- git tag $TRAVIS_TAG

# Deploy a github release
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $github_token
  file: "Firebot-win32-x64.zip"
  on:
    repo: crowbartools/firebot-dev-builds
  name: Firebot dev build
  body: $TRAVIS_COMMIT_MESSAGE
  prerelease: true
